### ISSUE TITLE
Unable to open nfc device

### ISSUE THREAD

**Issue by CraggerYT** [xavave/Mifare-Windows-Tool#11]
When I click Write/Read Tag the error message "ERROR: Unable to open NFC device: acr122_usb:bus-0:\\.\libusb0-0255--0x072f-0x2200" shows up.

**Comment by xavave** [comment]
Dis you use libusbk ?

**Comment by CraggerYT** [comment]
Yes

**Comment by xavave** [comment]
I have no clue about this error. Do you know how to use visual studio 2019 ?

**Comment by CraggerYT** [comment]
only a little bit

**Comment by xavave** [comment]
could you please run again the InstallDriver.exe in ACR122_LibUsbK_Driver folder (typically in  C:\Program Files (x86)\AVXTEC\MWT)

**Comment by CraggerYT** [comment]
It did not work sadly.

**Comment by xavave** [comment]
could you show me a screenshot of the installation with InstallDriver.exe please

**Comment by CraggerYT** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/75689873/101527021-c13b6800-398d-11eb-9369-22edb17bd29a.png)

**Comment by xavave** [comment]
I can see that you have not installed the latest version: 7366.20643
could you install latest version please:  1.0.7499.42986 --> https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by CraggerYT** [comment]
I doesn't matter if I use the old or the new version. same Error

**Comment by xavave** [comment]
Sorry but I don't know how to reproduce this error
I need more information to help 
send me a pm on xavave [at] gmail.com

**Comment by xavave** [comment]
did you use a USB hub to plug the ACR122U ?

**Comment by CraggerYT** [comment]
no

**Comment by xavave** [comment]
I think I could reproduce the issue
![image](https://user-images.githubusercontent.com/3501675/101532624-1d55ba80-3995-11eb-9b04-885503cb9318.png)

what I did is disable my antivirus/ add myfarewindowstool to exclusion list:
![image](https://user-images.githubusercontent.com/3501675/101532900-758cbc80-3995-11eb-8e08-d2411b144da3.png)

![image](https://user-images.githubusercontent.com/3501675/101532957-89d0b980-3995-11eb-9267-63ff225a5182.png)

**Comment by CraggerYT** [comment]
I added the Program to Windows defender and same problem.

**Comment by xavave** [comment]
ok. so I don't know

**Comment by xavave** [comment]
is the light on your acr122U device green, red, or no light?

**Comment by CraggerYT** [comment]
red and if I put a tag on it it lights green

**Comment by xavave** [comment]
so I think it's a driver issue: when you use mifare windows tool, the libusbk driver makes the ACR 122U have NO LIGHT
(not red, not green)
so you should reinstall LIBUSB Driver this way:http://legacy.averbouch.biz/libnfc-and-nfc-utils-binaries-on-windows-10/#howtouse

**Comment by CraggerYT** [comment]
I have downloaded the exact same and no I reinstalled it and still the same problem.

**Comment by xavave** [comment]
did you also install Native driver?
You need to have **no light** on the ACR122U, **if you have red or green, it will not work with mifare windows tool**

**Comment by CraggerYT** [comment]
I think I have installed the native drive for the fifth time now, cause I tried so much allready

**Comment by xavave** [comment]
really sorry if I cannot help you better ...

**Comment by CraggerYT** [comment]
Thanks. I will try deleteing everything and reinstall .

**Comment by CraggerYT** [comment]
Hello.
I solved the Problem. I just had a fake acr122u.

**Comment by cenzo85** [comment]
Hi, I have the same problem or quite the same.
If I installe the original driver the light of the reader is RED and became GREEN when I put a card on the reader.
After the installation of libusbk the light of the reader swich off (on the list of windows peripheral it appear like correcly installed), so I have the same problem "Unable to read Usb ... "

How do you have undetand taht your acr122u is a fake ?
