### ISSUE TITLE
Unable to copy the RFID tag

### ISSUE THREAD

**Issue by Thibk-luni** [xavave/Mifare-Windows-Tool#12]
Hi,
I try to copy the RFID tag of my building.
When opening Mifare for Windows, and clicking on Read. My computer is writing a lot of code lines but i am not able to save it, so i can copy it to a new rfid tag
Can anyone help me ?
Thanks a lot

**Comment by Thibk-luni** [comment]
When i use my android device to do it, i am able to copy and past the dump to a new tag but sector 0 is not the same thus the new tag is not working

**Comment by xavave** [comment]
be careful to the fact that some chinese tags are only comptabile with android and others only with libnfc
