### ISSUE TITLE
Incorrect writing to Mifare Classic 1K card

### ISSUE THREAD

**Issue by deReeperJosh** [xavave/Mifare-Windows-Tool#13]
I wrote to my mifare classic 1K cards with the attached dump files, but this broke the cards and they are no longer recognised as Mifare classic cards. Is there something wrong with these dump files? The access bits are all correct for every sector.

[dumpfiles.zip](https://github.com/xavave/Mifare-Windows-Tool/files/5742517/dumpfiles.zip)

**Comment by xavave** [comment]
I'm not an expert about ACs but I think your access bits are too restrictive 
I've edited your dump 'charge.dump' and modified ACs like this with AC: **FF0769** (with an hex editor)
![image](https://user-images.githubusercontent.com/3501675/103156758-76eb2100-47ac-11eb-84f7-a2f51cf8eb93.png)

here is the modified dump. could you try again to write a tag with this modified dump?
[charge_ACs_modified.zip](https://github.com/xavave/Mifare-Windows-Tool/files/5743489/charge_ACs_modified.zip)

**Comment by deReeperJosh** [comment]
Unfortunately, it still produces the same error. I think it could be to do with the style of card I am using, as one other type of card have no trouble being re-read using your tool.

![mifare](https://user-images.githubusercontent.com/28370004/103158349-983a2480-4821-11eb-835b-72f4b1d8dba9.png)

**Comment by deReeperJosh** [comment]
The screenshot above was produced after writing the modified dump to the card and then trying to read the same card again.

**Comment by xavave** [comment]
yes, probably that the style of card you are using is not compatible

**Comment by GorkaLandaburu** [comment]
Sorry for not being an expert but I do not understand why I cannot copy back a previously dumped card.

Guessing size: seems to be a 1024-byte card
Writing 64 blocks |...........................................xxxfailed to write trailer block 47 
xxxxfailed to write trailer block 51 
x............|
Done, 55 of 64 blocks written.

Any clue? Am I missing something?

**Comment by xavave** [comment]
> Sorry for not being an expert but I do not understand why I cannot copy back a previously dumped card.
> 
> 
> 
> Guessing size: seems to be a 1024-byte card
> 
> Writing 64 blocks |...........................................xxxfailed to write trailer block 47 
> 
> xxxxfailed to write trailer block 51 
> 
> x............|
> 
> Done, 55 of 64 blocks written.
> 
> 
> 
> Any clue? Am I missing something?

Maybe because AC of the original card are restrictive so then you cannot write these blocks again
