### ISSUE TITLE
Enhancement: Add option for driver ACR1252

### ISSUE THREAD

**Issue by keldnorman** [xavave/Mifare-Windows-Tool#14]
I installed the driver and it works fine for a ACR1252 reader.

But the Mifare-Windows-Tool does not 

Would it be hard to add that support to it ?

**Comment by xavave** [comment]
I have no idea , I don't have any ACR1252 in order to test
did you install libusbk wrapper over the native ACR1252  ?

**Comment by keldnorman** [comment]
It is the same driver so it should just work exactly as the one you have. 
I were hoping that the program looks for a specific model and you could just add the other model (ACR1252) to the list.
Nevermind then - I'll find the right model / same reader that you have and try it out.

:)

**Comment by xavave** [comment]
> It is the same driver so it should just work exactly as the one you have.
> I were hoping that the program looks for a specific model and you could just add the other model (ACR1252) to the list.
> Nevermind then - I'll find the right model / same reader that you have and try it out.
> 
> :)

okay, but did you install the driver wrapper libusbK ?this is mandatory to run with libnfc and so with Mifare windws tool
