### ISSUE TITLE
Résolu : "Write tag" doesn't work

### ISSUE THREAD

**Issue by nova-06** [xavave/Mifare-Windows-Tool#15]
when I click on the "write tag" button of the latest version in windows 10, it opens the "read tag" button function, in the french version. Unable to write a tag. Have you a solution ? Thx
![Capture d’écran 2021-04-01 104038](https://user-images.githubusercontent.com/48548005/113267474-af802680-92d6-11eb-9a0c-7aa49264ef6c.jpg)

**Comment by xavave** [comment]
in order to be able to write badge you need to read it once at first, because writing process needs to "know" what is already on the badge
for that you need to choose keys (extended or french or std) then decode and read badge.

**Comment by xavave** [comment]
After your comments, I've released a new version of Mifaer Windows tool a few minutes ago, I hope it will be easier to use !
https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by nova-06** [comment]
Merci. La màj a résolu le problème d'écrire de badge.
