### ISSUE TITLE
bonjour, le programme suite à la mise à jour ne fonctionne plus depuis le 01/04/2021

### ISSUE THREAD

**Issue by christianjou** [xavave/Mifare-Windows-Tool#16]
le programme ne se lance plus. Je suis sur windows 10

**Comment by nova-06** [comment]
Bonjour,
Il faut désinstaller votre version actuelle et réinstaller l'application. J'ai eu le problème ce matin, et je l'ai résolu ainsi.

**Comment by christianjou** [comment]
Ok Merci. Résolu

**Comment by fernandossmm** [comment]
In english, if it's not loading after installing the update, just desintall both programs from the control panel and reinstalling the new version
