### ISSUE TITLE
Card is not vulnerable to nested attack

### ISSUE THREAD

**Issue by christianjou** [xavave/Mifare-Windows-Tool#17]
bonjour, que faire dans ce cas svp ?

**Comment by DeenOConnor** [comment]
Hello.
Message "card is not vulnerable to nested attack" is produced by mfoc when the card is, well, not vulnerable.
There's an edited version of mfoc that supports hard nested attack:
https://github.com/nfc-tools/mfoc-hardnested

I suggest reading [this](https://www.cs.ru.nl/~rverdult/Ciphertext-only_Cryptanalysis_on_Hardened_Mifare_Classic_Cards-CCS_2015.pdf) if you want more info.

**Comment by xavave** [comment]
> Hello.
> Message "card is not vulnerable to nested attack" is produced by mfoc when the card is, well, not vulnerable.
> There's an edited version of mfoc that supports hard nested attack:
> https://github.com/nfc-tools/mfoc-hardnested
> 
> I suggest reading [this](https://www.cs.ru.nl/~rverdult/Ciphertext-only_Cryptanalysis_on_Hardened_Mifare_Classic_Cards-CCS_2015.pdf) if you want more info.

You can try to replace the mfoc I use in Mifare windows tool with the edited version that I had already cross-compiled (see here : 
https://legacy.averbouch.biz/libnfc-and-nfc-utils-binaries-on-windows-10/#mfoc_hardnestedhttps://legacy.averbouch.biz/libnfc-and-nfc-utils-binaries-on-windows-10/#mfoc_hardnested ) or, directly in this attachment:
[mfoc_hardnested.zip](https://github.com/xavave/Mifare-Windows-Tool/files/6425536/mfoc_hardnested.zip)
after unzipping this mfoc_hardnested.zip , just rename (for backup) the mfoc.exe in C:\Program Files (x86)\AVXTEC\MWT\nfctools\ and copy this unzipped mfoc (hardnested version) in this same directory (with name mfoc.exe)
(The old mfoc.exe size is 126KB and the mfoc hardnested file size is 1630 KB)
Please then tell us here if it's working better or not

**Comment by christianjou** [comment]
Super. Je vais essayer de suite

**Comment by xavave** [comment]
> Super. Je vais essayer de suite

est ce que ca a fonctionné ?

**Comment by christianjou** [comment]
Bonjour, au premier lancement pour la lecture de la clef : NON.
J'ai eu ce méssage 
<img width="439" alt="Capture d’écran 2021-05-07 à 11 27 49" src="https://user-images.githubusercontent.com/72012052/117437849-12e22180-af31-11eb-8706-68358aefeb01.png">

J'ai donc rajouté cette dll et cela à fonctionné, mails malheureusement cela n'a pas suffit à décrypter ma clef car j'ai eu ensuite ce méssage : 
<img width="401" alt="Capture d’écran 2021-05-07 à 12 36 16" src="https://user-images.githubusercontent.com/72012052/117438025-48870a80-af31-11eb-85f6-015f84696a38.png">


Donc la question est : serait il possible d’augmenter le nombres de "Probes" ? et là je pense que le programme trouverait les clefs.

**Comment by xavave** [comment]
Hi, I've just published a new version (1.0.7805.26681) with 2 new options:
just check this checkbox and try to read your badge again
![image](https://user-images.githubusercontent.com/3501675/118361777-27579700-b58d-11eb-82d4-67ddb66e04d4.png)

this "advanced" option is available after clicking on "read tag" button:
![image](https://user-images.githubusercontent.com/3501675/118361818-4b1add00-b58d-11eb-96bb-7874fcae4890.png)

**Comment by christianjou** [comment]
bonjour, je vais essayer et te faire un retour. Je pense que ça va être au top. Merci pour la prise en compte c'est génial

**Comment by christianjou** [comment]
Bonjour, et bien c'est nickel. J'ai pu trouver mes codes. Parfait. Il n'y a que la partie édition du dump qui ne fonctionne pas correctement. Je ferais une "issue" sur un autre post. Très grand merci.
