### ISSUE TITLE
Editing Dump File makes Software freeze

### ISSUE THREAD

**Issue by ITC-NC** [xavave/Mifare-Windows-Tool#18]
Bonjour, j'ai téléchargé la version V1.0.7499.42986 et la version V1.0.7769 afin de réaliser des tests de ré-encodage d'une carte Mifare classic 1K.
La lecture d'une carte fonctionne très bien, le clonage d'une carte à partir d'un DUMP fonctionne très bien, cependant dès que j'essaye d'éditer un DUMP d'une carte, l'application se freeze et la consommation de RAM ne fait qu'augmenter jusqu'à atteindre la saturation.
J'ai 8Go de RAM et j'utilise W10.

Cordialement,

**Comment by xavave** [comment]
Merci pour votre retour, je vais regarder ça de plus près

**Comment by christianjou** [comment]
bonsoir, idem pour moi

**Comment by xavave** [comment]
malheureusement , je ne parviens pas a reproduire ce bug
je serais tenté de faire une session de deboggage a distance sur votre pc si vous êtes d'accord , si oui envoyez moi un message en privé svp.merci

**Comment by xavave** [comment]
it's now fixed --> just install latest msi version: https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.7776.36318

**Comment by christianjou** [comment]
merci
