### ISSUE TITLE
Error: Tag Was Removed

### ISSUE THREAD

**Issue by ZaKXS** [xavave/Mifare-Windows-Tool#19]
When i try to write on an 13.56MHz NFC card i get this error:

`NFC reader: ACS / ACR122U PICC Interface opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): 43  12  39  03  
      SAK (SEL_RES): 08  
RATS support: no
Guessing size: seems to be a 1024-byte card
Sent bits:     50  00  57  cd  
Sent bits:     40 (7 bits)
Warning: Unlock command [1/2]: failed / not acknowledged.
Writing 64 blocks |xxxfailed to write trailer block 3 
x!
Error: tag was removed`

I do the following when trying to write it:
- First i read it so it can get the keys. All ok
- Then i write with the following parameters:
![image](https://user-images.githubusercontent.com/83012784/115708753-ac75d480-a370-11eb-8084-2d29ff776a86.png)

- And i get the error:
![image](https://user-images.githubusercontent.com/83012784/115708847-c9120c80-a370-11eb-96a3-58352ccb0385.png)

**Comment by xavave** [comment]
Hi,
Can you try with option "chinese magic direct/CUID/gen 2(C)" ?

**Comment by ZaKXS** [comment]
I need the gen 1 option to get what i need. But i tried what u said anyways and got this:
![image](https://user-images.githubusercontent.com/83012784/115731123-2913ad80-a387-11eb-983a-73126e07ce00.png)

I tried if the card works after this operation but it doesn't.

**Comment by ZaKXS** [comment]
Just noticed that after doing the last thing, the card broke or something. I cannot write anything anymore or format/erase its cotent. When i try to write something i get this:

**Comment by ZaKXS** [comment]
Just noticed that after doing the last thing, the card broke or something. I cannot write anything anymore or format/erase its cotent. 
When i try to write something i get this:
![image](https://user-images.githubusercontent.com/83012784/115732061-f0c09f00-a387-11eb-8b3b-844281660026.png)

When i try to factory format, it just crashes.

**Comment by clemon79** [comment]
I'm having this same problem and I'm pretty sure I have all of libUsbk drivers wrapped and installed correctly. It does things like changing the UID just fine but it pukes at writing the blank or writing a dump. And it looks like its happening AFTER that Sector 0 write.
![image](https://user-images.githubusercontent.com/22535391/152707984-bfb1b3ca-2d32-4bfa-a4a1-b5482df77f3b.png)

**Comment by Krypt0896** [comment]
> 

Skylanders? 
where did you get the files ? as i know theres alot of fakes going around.
60/64 written means theres a problem with the file not the software 
also you need to convert them from .bin to .dmp.
get rid of the .key in the file name also only .dmp is needed 

I can send my files over if all else fails

**Comment by razorspade** [comment]
> > 
> 
> Skylanders? where did you get the files ? as i know theres alot of fakes going around. 60/64 written means theres a problem with the file not the software also you need to convert them from .bin to .dmp. get rid of the .key in the file name also only .dmp is needed
> 
> I can send my files over if all else fails

I have the same error... I also tried the "blank" file same error .

I also tried different USB ports. Any ideas ?

**Comment by xavave** [comment]
> > > 
> > 
> > 
> > Skylanders? where did you get the files ? as i know theres alot of fakes going around. 60/64 written means theres a problem with the file not the software also you need to convert them from .bin to .dmp. get rid of the .key in the file name also only .dmp is needed
> > I can send my files over if all else fails
> 
> I have the same error... I also tried the "blank" file same error .
> 
> I also tried different USB ports. Any ideas ?

Hi, could you re-check libusbK settings : https://github.com/xavave/Mifare-Windows-Tool/issues/27#issuecomment-1013954154

**Comment by razorspade** [comment]
> > > > 
> > > 
> > > 
> > > Skylanders? where did you get the files ? as i know theres alot of fakes going around. 60/64 written means theres a problem with the file not the software also you need to convert them from .bin to .dmp. get rid of the .key in the file name also only .dmp is needed
> > > I can send my files over if all else fails
> > 
> > 
> > I have the same error... I also tried the "blank" file same error .
> > I also tried different USB ports. Any ideas ?
> 
> Hi, could you re-check libusbK settings : [#27 (comment)](https://github.com/xavave/Mifare-Windows-Tool/issues/27#issuecomment-1013954154)

I have now tried again -( as in the pictures - also successful according to Windows) unfortunately still the same error
is it normal that the LED always stays off ?
at the first try it was for a short time green

**Comment by xavave** [comment]
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > Skylanders? where did you get the files ? as i know theres alot of fakes going around. 60/64 written means theres a problem with the file not the software also you need to convert them from .bin to .dmp. get rid of the .key in the file name also only .dmp is needed
> 
> > > > I can send my files over if all else fails
> 
> > > 
> 
> > > 
> 
> > > I have the same error... I also tried the "blank" file same error .
> 
> > > I also tried different USB ports. Any ideas ?
> 
> > 
> 
> > Hi, could you re-check libusbK settings : [#27 (comment)](https://github.com/xavave/Mifare-Windows-Tool/issues/27#issuecomment-1013954154)
> 
> 
> 
> I have now tried again -( as in the pictures - also successful according to Windows) unfortunately still the same error
> 
> is it normal that the LED always stays off ?
> 
> at the first try it was for a short time green

Yes the light stays off when the libusbk driver is properly installed

**Comment by EdgeFaction** [comment]
I started to also receive this error recently. Maybe in early January. I hadn't upgraded MWT or libusbk. It just started happening for card batches and source images that it wasn't before. I tested a brand new install on a different PC and am experiencing the same issue. I generally always get a Error tag was removed message. 

I'm wondering if it is related to recently Windows 10 updates that are effecting the NFCtools compile. Now I notice that when a card is placed on the device I get a smart card showing up in the device manager - sometimes uninstalling this as a device gets the writing to work, but it doesn't seem to be consistent.

My next course of action is to trying to use a docker image with linux, the acr122u driver, and nfctools to see if that will do it correctly.

**Comment by Maceika** [comment]
I HAVE FOUND THE SOLUTION! THE REASON THE ERROR SHOWS UP MEANS YOU HAVE THE WRONG CARDS, BUY NEW ONES THAT ACTUALLY WORK.

**Comment by xDerApfelx** [comment]
> I HAVE FOUND THE SOLUTION! THE REASON THE ERROR SHOWS UP MEANS YOU HAVE THE WRONG CARDS, BUY NEW ONES THAT ACTUALLY WORK. I HAVE TRIED WITH A DIFFERENT PACK OF CARDS AND IT WORKED.

Could you send a link of the one you bought??
I want to use them for Skylanders too

**Comment by JonasWeckhuysen-ucll** [comment]
has someone the link to those cards?

**Comment by xavave** [comment]
> has someone the link to those cards?
> 
> 

Skylanders need UID Changeable Block O rewritable 1k s50 13.56Mhz Chinese Magic Cards to work. Maybe these ones on aliexpress https://a.aliexpress.com/_Exd11zN
