### ISSUE TITLE
Bad data opening Mifare Classic Tool dumps

### ISSUE THREAD

**Issue by Knocks83** [xavave/Mifare-Windows-Tool#2]
When you try opening a dump made by the Android app, you see strange data before the +Sector: 0 text (that you souldn't see).
![image](https://user-images.githubusercontent.com/22529815/87253458-ad8de300-c47b-11ea-9a8b-9868e39a11c5.png)

**Comment by xavave** [comment]
@Knocks83 hi Knocks, could you send me your dump file in pm please ?

**Comment by Knocks83** [comment]
No, I'm pretty sure it's MWT to have problems.
That's my first dump (I changed it to share it, but it gives me the same problem):
```
+Sector: 0
B72E6263980804006263646566676869
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
+Sector: 1
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
+Sector: 2
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
+Sector: 3
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
```

and this is what it shows:
![image](https://user-images.githubusercontent.com/22529815/87285846-4f531580-c4f8-11ea-916c-5e2cdb4ace03.png)
 
You suggested me to use your conversion software, so I did and the result is an hex file containing the following:

```
00000000: B7 2E 62 63 98 08 04 00 62 63 64 65 66 67 68 69
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00000030: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF 
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000070: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF 
00000080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000000a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000000b0: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF
000000c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000000d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000000e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000000f0: FF FF FF FF FF FF FF 07 80 69 FF FF FF FF FF FF
```
and, even if it doesn't contain the junk data before the dump, it still has some problems:
![image](https://user-images.githubusercontent.com/22529815/87286280-f33cc100-c4f8-11ea-9921-e51aa8b77f87.png)

now the sectors are merged, showing 2 sectors in 1 (under the 5th line there should be a +Sector split).

**Comment by xavave** [comment]
Hi again,
MCT dump files are in test format whereas MWT dump files are in hex format. 
They are different , do you understand the difference between hex format and text format ?
on the conversion software you see good data but with bad sector split, but it shows that when you convert text data to hex data you get the good dump data. I don't have any clue for now to get the sector size on my convertion software , so it's only for mifare 1K cards for now

![image](https://user-images.githubusercontent.com/3501675/87290170-f1293100-c4fd-11ea-99f4-9fe98b95e1db.png)

if you click on show in ASCII button 
![image](https://user-images.githubusercontent.com/3501675/87290212-fedeb680-c4fd-11ea-99ac-5a961889eaec.png)
you will see better the text data of your MCT dump

BUT the purpose of MWT is not to convert dumps from MWT. 
I can make some improvements but at first I need to understand what you want to do. Could you explain please ?

**Comment by xavave** [comment]
@Knocks83 Hi again, I've added an automatic conversion from MCT files. Can you re-test with this new release please?
https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.7450.24466

**Comment by Knocks83** [comment]
Sadly it doesn't work. The dump still has 
```
2B536563746F723A20300A3944343332
42373438313839303430304338303830
30323030303030303031370A36323030
34383838343938383441383834423838
```
before +Sector: 0.

**Comment by xavave** [comment]
@Knocks83 sorry I've uploaded the wrong version on msi file, I will update it in a few minutes

**Comment by xavave** [comment]
@Knocks83 done: https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.7499.42986

**Comment by Knocks83** [comment]
It works, thanks!
