### ISSUE TITLE
Read/Write Error

### ISSUE THREAD

**Issue by githubcomment** [xavave/Mifare-Windows-Tool#20]
Running Windows 7 ultimate via VirtualBox on Mac (11.3.1).

I can successfully activate any of the buttons except "Read Tag" or "Write Tag" - when I try, I receive the following error message:

![ErrorMsg](https://user-images.githubusercontent.com/85450912/120931862-ffa1ad80-c6b8-11eb-9925-6fdc2b0c9955.png)

**Comment by xavave** [comment]
Are you on 32 or 64 bit windows 7 virtual machine ?

**Comment by githubcomment** [comment]
64 bit

**Comment by xavave** [comment]
Read ne write taf use mfoc executable which you can find in tools folder inside app. Mfoc executable is compiled for windows 64. Maybe you have to change some settings in your vm ?

**Comment by xavave** [comment]
Hi, I have installed windows 7 64 bits on Virtualbox , and I had the same issue than you 
you need to connect ACR 122U inside VM:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/3501675/147414880-4c48b6c9-3e0e-4eed-8a76-25191bd02cad.png">

I could then make it work 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/3501675/147414909-85b99e21-2c5a-40b8-ad0b-e232380b753a.png">

you maybe need to install driver from here: C:\Program Files (x86)\AVXTEC\MWT\ACR122_LibUsbK_Driver
--> InstallDriver,  after windows 7 has recognized ACR 122U in usb:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/3501675/147414934-4ef4f71d-4f57-495f-925d-9896eea00f6c.png">
