### ISSUE TITLE
Problem during the write process

### ISSUE THREAD

**Issue by Melsi96** [xavave/Mifare-Windows-Tool#21]
i can't overwrite the dump because i can't select the file where i put my keys. How can i manage this problem?
![mifare](https://user-images.githubusercontent.com/73393184/121214320-4b05b880-c87f-11eb-8c92-4efb6e45976e.png)

**Comment by xavave** [comment]
you need to select source dump
![image](https://user-images.githubusercontent.com/3501675/121224927-4e9e3d00-c889-11eb-9f67-8d5304fad514.png)
you need also to check if the other "select keys" window is not hidden behind the main window

**Comment by Melsi96** [comment]
yes i had selected le source of dump, but the program can't overwrite, i think that the problem is the missing keys. 
![mifare2](https://user-images.githubusercontent.com/73393184/121317416-8ef1cf80-c90a-11eb-8cb1-8ec88b140bfc.png)

**Comment by Melsi96** [comment]
no window appear when i select "write tag"

**Comment by Melsi96** [comment]
ok thankssss, now it works perfectly
