### ISSUE TITLE
Which option to choose for FUID tags

### ISSUE THREAD

**Issue by riyas1980** [xavave/Mifare-Windows-Tool#22]
Hello,

I have few FUID tags (Bloc 0 can only be written once.). if I Choose write Tag, I have 3 options :
1) Not 0 writable (w)
2) Chinese magic unlocked/gen1 (W)
3) Chinese magic direct/CUID/gen2 (C)

If I choose Enable writing to manufacturer block, only option 2 is available. If I choose option 3, enable writing is automatically unchecked.

For this kind of badges, how can we copy ?

Thanks for your help

**Comment by xavave** [comment]
Hello,

you should choose options 2 or 3 
If you choose option 3 (Chinese magic direct/CUID/gen2 (C)) , enable writing is automatically unchecked ? 
did you try with option 2 ?
