### ISSUE TITLE
ERROR: Unable to open NFC device: acr122_usb:bus-0:\\.\libusb0-0255--0x072f-0x2200

### ISSUE THREAD

**Issue by costivl** [xavave/Mifare-Windows-Tool#23]
Hello,

I am getting the following error when i try to connect my ACR122U-A9 to the Mifare Windows Tool:

nfctools\nfc-list.exe uses libnfc 1.7.1
ERROR: Unable to open NFC device: acr122_usb:bus-0:\\.\libusb0-0255--0x072f-0x2200
No Tag detected on reader

I did the following steps:

Installed Native driver from here : https://www.acs.com.hk/en/driver/3/acr122u-usb-nfc-reader/  –> MSI Installer for PC/SC Driver
Installed libusbk from here: https://sourceforge.net/projects/libusbk/

After installing libusbK driver, the ACR122U will still show the green light and plays a sound when a card is used, this shouldnt happend!

When i do kList.exe it shows me:

C:\libusbK-dev-kit>kList.exe

Loading USB ID's maintained by Stephen J. Gowdy <linux.usb.ids@gmail.com>..

 1. ACR122U PICC Interface (Advanced Card Systems, Ltd) [Connected]
    Service              : libusbK
    ClassGUID            : {ECFB0CFD-74C4-4F52-BBF7-343461CD72AC}
    DeviceID             : USB\VID_072F&PID_2200\A02014090501
    DeviceInterfaceGUID  : {3321875C-24D2-5290-67C6-C0BD73FA5D81}
    SymbolicLink         : \\?\usb#vid_072f&pid_2200#a02014090501#{3321875c-24d2-5290-67c6-c0bd73fa5d81}
    DevicePath           : \\?\usb#vid_072f&pid_2200#a02014090501#{3321875c-24d2-5290-67c6-c0bd73fa5d81}
    SerialNumber         : A02014090501
    BusNumber            : 0
    DeviceAddress        : 2

Any sugestions? 

Thank you

**Comment by xavave** [comment]
hi,
you said : After installing libusbK driver, the ACR122U will still show the green light and plays a sound when a card is used, this shouldnt happend! --> did you follow my explanations here? https://github.com/xavave/Mifare-Windows-Tool/issues/27
