### ISSUE TITLE
Compare .mct with .dump

### ISSUE THREAD

**Issue by xDonatello** [xavave/Mifare-Windows-Tool#25]
If in "Compare dumps" I try to compare a .mct with a .dump, the program crashes.

**Comment by xavave** [comment]
hi, could you try again with the new version please? https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8030.27704

**Comment by xDonatello** [comment]
> hi, could you try again with the new version please? https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8030.27704

Now it doesn't crash, however it returns random values regarding the .dump file.
Also, as you can see from the screenshot, it has a confusing order.

![image](https://user-images.githubusercontent.com/13498803/147503099-04921eb8-5512-4f85-b07a-8864fe1df7d8.png)

**Comment by xavave** [comment]
could you please send me your mct and also your dump file ?
do you know that the file formats are differents ?
maybe you just need to convert mct file to dump file then you can compare them properly : I've made a converter that  you can find here: https://github.com/xavave/bm-mifare-classic/releases

**Comment by xDonatello** [comment]
> 

I know they are different.
If it is possible to make a direct comparison, which then converts and compares directly, it would be convenient.
If that's not possible, you should add an error message.

In this case, I was trying to compare the same file, one in .mct and one in .dump
Do I have to send them to you? Where can I send them to you?

**Comment by xavave** [comment]
Okay, I now understand your needs. So I just need to take a dump, convert it and I can use it for testing this new feature of comparing mct/dump

**Comment by xavave** [comment]
[MifareWindowsTool_v1.0.8030.27704.zip](https://github.com/xavave/Mifare-Windows-Tool/files/7782159/MifareWindowsTool_v1.0.8030.27704.zip)
Here is a pre-release, could you please test it and tell me if it's working fine for you?
I've added dump conversion on the fly when comparing 2 dumps

![image](https://user-images.githubusercontent.com/3501675/147516518-3654baa0-88b6-4862-b2db-52e92c3a0b42.png)

**Comment by xDonatello** [comment]
> [MifareWindowsTool_v1.0.8030.27704.zip](https://github.com/xavave/Mifare-Windows-Tool/files/7782159/MifareWindowsTool_v1.0.8030.27704.zip) Here is a pre-release, could you please test it and tell me if it's working fine for you? I've added dump conversion on the fly (text/binary) when comparing 2 dumps

I confirm. Now it works.
Great work 😉 Thank you

**Comment by xDonatello** [comment]
@xavave Sorry, now a problem has arisen.
If I try to open an .mct file from "Edit/Analyze file dump", the program crashes.

**Comment by xavave** [comment]
@xDonatello I've just tried to reproduce this issue but it works for me with a .mfd file. Could you send me your dump to xavave [at] gmail dot com please?

**Comment by xDonatello** [comment]
> @xDonatello I've just tried to reproduce this issue but it works for me with a .mfd file. Could you send me your dump to xavave [at] gmail dot com please? [by the way, mifare windows tool is not natively made to read android mct files, but I will try to add this option for edit dump too...]

.mfd is equivalent to .dump, which is a binary file, and it works.
I tried with a .mct, which is a text file. It worked before this update.

I have tried with different .mct files and they all give the same result, if necessary I will send you some.

**Comment by xavave** [comment]
@xDonatello you were right, I've fixed it in latest version https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8033.34063
if you would like to test please?
thanks

**Comment by xDonatello** [comment]
> @xDonatello you were right, I've fixed it in latest version https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8033.34063 if you would like to test please? thanks

Immediately! And I confirm that now it works again 🙂
Thanks to you

**Comment by xDonatello** [comment]
> could you please send me your mct and also your dump file ? did you know that the file formats between .mct and .dump are differents ? maybe you just need to convert mct file to dump file then you can compare them properly : I've made a converter that you can find here: https://github.com/xavave/bm-mifare-classic/releases

At this point, I only have one last request, if possible.
That is, allow the saving of a dump in textual (.txt/.mct)

So that your "mct2dmp Gui" is no longer needed, and then include its functionality here in MWT.

**Comment by xavave** [comment]
allow the saving of a dump in textual (.txt/.mct) (dump conversion from/to mifare classic / mifare windows)
<img width="98" alt="image" src="https://user-images.githubusercontent.com/3501675/147703640-218b34ea-fb12-4f72-ae95-fa1a932079ff.png">

![image](https://user-images.githubusercontent.com/3501675/147703658-2c4a19bf-8b80-4241-a53a-0db489d5d856.png)

https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8033.39813

**Comment by xDonatello** [comment]
> allow the saving of a dump in textual (.txt/.mct) (dump conversion from/to mifare classic / mifare windows)
> https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8033.39813

Great! Thanks
