### ISSUE TITLE
Got errors with the new version

### ISSUE THREAD

**Issue by Tiwas** [xavave/Mifare-Windows-Tool#27]
Wanted to write a new card today, and got the following errors:
![image](https://user-images.githubusercontent.com/17053402/149669991-60702635-3df8-4731-a2e0-9203faa6ebd4.png)

I tried both copying an existing nfc card, and writing a previous dump. Reading seems to work (however, it was unable to find the keys itself).

Is this a user error?

**Comment by xavave** [comment]
When you wrote previous dumps , the copy was working ?

**Comment by Tiwas** [comment]
I"ve used that dump before on my Linux box, so it should work fine. I also tried making a new dump just to make sure and got the same error. The cards should be magic, but I also tried without writing the uid. And I tried using both A and B key. I"m going to download an earlier build just to make sure.

**Comment by Tiwas** [comment]
Ok, so I uninstalled all drivers and such, just to test. I get a prompt upon starting the application saying the following:
![image](https://user-images.githubusercontent.com/17053402/149677407-33eb8f48-1b6d-49c8-b40f-314f0128e490.png)

I installed the native driver with the reader unplugged, then installed **libusbK-3.1.0.0-setup.exe**. After this, I still get the message above. Not sure why the application wants to reinstall, but unless I do it it says it access the reader. The light on the reader stays red, but I'm allowed to read the card I put on. No errors. If I try to write to it, it'll say the card is known and wants to know if I still want to read it. I select yes, it reads, but nothing happens. Same thing happens if I go back to try and write to it again. If I select "no", I get to the "write tag" dialog. I select "Write Dump (Clone)", "Use these access...", "Use Key A", select a source dump I just made and click "Start Cloning". This time it worked, but it's failed at least 10 times. Doing it again with the same card makes it fail. Trying to format cards just make the app force close.

Any idea as to what I should do?

**Comment by xavave** [comment]
did you install libusbk with CLIENT installer ?
![image](https://user-images.githubusercontent.com/3501675/149678310-a926171e-51c9-438b-a329-7a029f495666.png)
after installing, you need to install the client as I explained here: http://legacy.averbouch.biz/fr/libnfc-and-nfc-utils-binaries-on-windows-10/#howtouse

1- you should not have the red light still on, with libusbk properly installed
2- are the card you are writing on are new, never used cards ?

**Comment by Tiwas** [comment]
Using your link, I don't get the same steps as in the doc. Could it be another executable?
![image](https://user-images.githubusercontent.com/17053402/149678495-8bdc1729-d581-46f9-bfe1-9cf9eb0b0442.png)
![image](https://user-images.githubusercontent.com/17053402/149678504-4b324d5e-b5a4-4b99-9e33-ea38b116d7a8.png)
![image](https://user-images.githubusercontent.com/17053402/149678518-3815f792-73c7-46a7-bdd2-dd66c57c6b09.png)
![image](https://user-images.githubusercontent.com/17053402/149678528-829b67c2-c16c-40d0-9aa6-b04c3c9a1160.png)

Changed the usb port (again), and it's now green. It used to be green before...This is from device manager:
![image](https://user-images.githubusercontent.com/17053402/149678592-c75c7095-cebb-48a5-9d76-0b059c5e694b.png)

**Comment by Tiwas** [comment]
Now, factory format makes the application crash...

**Comment by xavave** [comment]
I've just tried the new driver: the red led should stay off after unpluging and repluging the ACRE 122U
here is what I did to install the new libusbk 3.1.0.0 (full procedure)

![image](https://user-images.githubusercontent.com/3501675/149678959-bcc415da-716b-4442-800a-eaf32a57c9ea.png)
![image](https://user-images.githubusercontent.com/3501675/149678972-41898b71-000f-42e1-b615-b4ce034dc8f8.png)
this next step is optional (answer YES if this window appears)
![image](https://user-images.githubusercontent.com/3501675/149678990-847a5c14-d7b1-4956-bf8c-182a7f4be16c.png)
![image](https://user-images.githubusercontent.com/3501675/149679019-4d30f808-9781-44ba-8fb4-1e1e8422f924.png)
![image](https://user-images.githubusercontent.com/3501675/149679047-6a45ce17-b1bf-413d-9d46-ba9caf50fe68.png)
import step : plug your ACR122U to display it in the list below:
![image](https://user-images.githubusercontent.com/3501675/149679076-d8a56e70-5673-4b2e-ad86-4ac83a37b340.png)
![image](https://user-images.githubusercontent.com/3501675/149679092-6a810b2d-380a-4708-a50c-cdab282daba9.png)
![image](https://user-images.githubusercontent.com/3501675/149679140-78578696-2162-460b-bc08-4f58c7273ffc.png)
![image](https://user-images.githubusercontent.com/3501675/149679161-7caefea9-ea30-44f8-897d-3d336b3e37a8.png)
![image](https://user-images.githubusercontent.com/3501675/149679170-5fde0c53-15de-42ab-8d3d-db3db47d89ce.png)

**Comment by xavave** [comment]
@Tiwas did you try ton reinstall libusbk as mentioned above ?

**Comment by Tiwas** [comment]
@xavave Yes, only minimal effect. The application no longer installs the driver on every restart, which I guess is a step in the right direction. I seem to have damaged three RFID cards before I got to write to one, but the reader to my building doesn't recognize it. I'm going to run the applications manually to see if there's any difference, but there shouldn't be.

**Comment by xavave** [comment]
@Tiwas  - you say "got errors with the new version"--> which version before did you try with no error ?

**Comment by Tiwas** [comment]
The last one I had was a preview you sent me. I didn't have any issues before yesterday, when I downloaded the latest version after the program prompted me to. I could, of course, be extremely unlucky with the last cards in my batch, though.

**Comment by xavave** [comment]
@Tiwas you can still download and install a previous version if you want to test: https://github.com/xavave/Mifare-Windows-Tool/releases

**Comment by Tiwas** [comment]
I think I found the issue, which is probably the executables you're running (the nfc executables).

This is the command I issued on my windows computer:
![image](https://user-images.githubusercontent.com/17053402/149897287-33755be6-045c-4045-9c0b-aa4667a40fcd.png)

I booted my ubuntu laptop with a PN533 NFC stick, and issued the same command - and it succeeded. I can now write to these cards again.

**Comment by xavave** [comment]
Good news. You wanted to erase the card, right?
So maybe I should try to recompile nfc-mfcclassic on windows. 
But on your screenshot I see there is still an error on block 0c?

**Comment by Tiwas** [comment]
As far as I understand, erasing doesn't work on non-"magic" cards, only on fobs that allow changing UID. I suspect it might be the way it was formatted left them in a non-functional state, but the recent nfc build I had on ubuntu managed to write to them.

I see two potential problems here:
1. If normal cards cannot be formatted (only overwritten with a blank copy), then there should be an option to just write a blank copy with FFFFFFFF as both A and B key. That would probably solve that issue. If electing to not use the blank image and insisting on actually formatting them, a warning should be given (but please double check if my understanding is correct).
2. Rebuilding the binaries (please make sure to include the hardnested fork) might make it possible to rewrite cards that have been left inoperable after misuse.

Thanks for helping out with the wrapper issue, and for actively listening to feedback :)

**Comment by xavave** [comment]
I already put a "blank card" file in the software that you can write on a card to simulate erase

**Comment by billw815** [comment]
have same issued here, but wasn't able to make one work... Keep saying 

NFC reader: ACS / ACR122U PICC Interface opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): bc  83  de  cd  
      SAK (SEL_RES): 08  
RATS support: no
Guessing size: seems to be a 1024-byte card
Sent bits:     50  00  57  cd  
Sent bits:     40 (7 bits)
Warning: Unlock command [1/2]: failed / not acknowledged.
Writing 64 blocks |xxxfailed to write trailer block 3 
x!
Error: tag was removed

when using chinese magic unlocked/gen1 (W)

when using not 0 writable (w)... write 63 on 63 blocks.

Can you help.

I'm already at my 10th cards no longer workable. When trying to Factory Format the card. Application on windows 10 keep crashing. Thanks

**Comment by billw815** [comment]
this is when using 0 writable... sorry. 

NFC reader: ACS / ACR122U PICC Interface opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): bc  83  de  cd  
      SAK (SEL_RES): 08  
RATS support: no
Guessing size: seems to be a 1024-byte card
Writing 64 blocks |xxfailed to write trailer block 3 
xxxxfailed to write trailer block 7 
xxxxfailed to write trailer block 11 
xxxxfailed to write trailer block 15 
xxxxfailed to write trailer block 19 
xxxxfailed to write trailer block 23 
xxxxfailed to write trailer block 27 
xxxxfailed to write trailer block 31 
xxxxfailed to write trailer block 35 
xxxxfailed to write trailer block 39 
xxxxfailed to write trailer block 43 
xxxxfailed to write trailer block 47 
xxxxfailed to write trailer block 51 
xxxxfailed to write trailer block 55 
xxxxfailed to write trailer block 59 
xxxxfailed to write trailer block 63 
x|
nfc_initiator_transceive_bytes: Mifare Authentication Failed
Done, 0 of 64 blocks written.
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed
nfc_initiator_transceive_bytes: Mifare Authentication Failed

**Comment by xavave** [comment]
hi @billw815 you tried with 10 cards , but I always see the same uid in your paste : UID (NFCID1): bc 83 de cd
which steps did you proceed to write these cards ?

**Comment by Tiwas** [comment]
@billw815 : Are you sure these are in fact UID unlocked? As far as I've heard only fobs can be unlocked, while cards for some reason cannot. Keep in mind, this is only something I read while looking for a solution to the problem I had.

Also, are you using the latest version of the software?

@xavave Did you recompile the binaries for the latest release? If so, maybe he should try it from the command line?

**Comment by xavave** [comment]
@Tiwas i did not recompile executables for the latest version.  Just some changes on my wrapper. 
But definitely it could be a good solution to test directly from command line
