### ISSUE TITLE
Reader answer transfer error

### ISSUE THREAD

**Issue by jay159876567890** [xavave/Mifare-Windows-Tool#29]
I was coding a card and this happened 
![6F188756-CB09-438D-9D07-BE13FE9E9B04](https://user-images.githubusercontent.com/96882777/152247492-7449528a-dc0f-4d75-ad9a-aa4778e88245.jpeg)
Any  idea on how to fix this

**Comment by xavave** [comment]
I has the same issue on some cards which were not compatible
