### ISSUE TITLE
Resizing the dump analyzer doesn't resize the text box

### ISSUE THREAD

**Issue by Knocks83** [xavave/Mifare-Windows-Tool#3]
Resizing the dump analyzer only adds gray space under the buttons, so with bigger dumps you have to scroll even with a big monitor.

**Comment by xavave** [comment]
Hi,
I've just fixed it (new  version)
https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.7450.24466

**Comment by Knocks83** [comment]
Still unfixed here.
![image](https://user-images.githubusercontent.com/22529815/87335015-e3949b00-c53f-11ea-8abc-e5db0befbb7e.png)

**Comment by xavave** [comment]
@Knocks83 sorry I've uploaded the wrong version on msi file, I will update it in a few minutes

**Comment by xavave** [comment]
@Knocks83 done: https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.7499.42986
