### ISSUE TITLE
No tag found

### ISSUE THREAD

**Issue by JeromeV10** [xavave/Mifare-Windows-Tool#30]
Salut ! J’ai un problème j’ai tout installé ma clef est bien détecté voici une photo 
![0C761E04-6C4F-4F38-A960-42FC4D28FC78](https://user-images.githubusercontent.com/99888204/154767618-0f5b2e59-a6f6-4f0c-8960-5ef84dc3d8f7.jpeg)

mais quand je veux Lire le badge pour modifier le solde il me met « ERROR: no tag found »  voici une photo 
![B1DEECB7-67DC-4A62-A369-807F99EF1877](https://user-images.githubusercontent.com/99888204/154767787-6826ecf1-fa32-48e4-aee6-542a1b70e5c3.jpeg)
![018E56E6-093A-4BD9-A9C6-25661523D975]

je ne comprend pas d’où ça viens si quelqu’un a une solution ça serait cool ça m’éviterais de passer par Kali 

ma clef est une Cogeskey 
![B58CBD9B-F525-46E2-B419-D48FA00E958E](https://user-images.githubusercontent.com/99888204/154767958-0f097c2a-0841-4d4a-afba-5419fb949250.jpeg)

merci à tout le monde :)

**Comment by xavave** [comment]
Salut 
Je pense que la clef n'est pas compatible avec mfoc
De plus en cherchant hack cogeskey sur Google j'ai trouvé ça :

https://www.abcelectronique.com/forum/showthread.php?t=40036
Dans ta clef il n’y a aucune somme de comptabilise il n’y a qu’un code qui identifie ta clef sur la machine

la somme que tu inseres dans la machine a cafe pour recharger ton compte se trouve memorise dans la machine a cafe pour le code se trouvant dans ta clef qui n’est qu’un transpondeur et tu ne pourras utiliser ton credit que sur cette machine a cafe et non pas sur la machine a cafe voisine

**Comment by JeromeV10** [comment]
Ah mince :(( merci quand même chef !
