### ISSUE TITLE
NFC Interface ACR122U vs ACR1252U

### ISSUE THREAD

**Issue by valeriogiampa** [xavave/Mifare-Windows-Tool#31]
Dear all,
I have bought the ACR122U and i have used it to copy some Mifare Classic 1k tag. Sometime I have registered a luttare bug.
I have contacted the NFC interface manufacturer to ask support and it has suggested to me to pass from ACR122U (no time supported) to rhe updated version ACR1252U. The deiver is the some but the Mifare Windows tool does not recognize it. how Can I use this new interfacce with Mifare Windows Tool?

**Comment by xavave** [comment]
Mifare Windows tool is just a wrapper on libnfc tools 
And I think Libnfc tools doesn't support the acr125u
