### ISSUE TITLE
Error Tag was removed

### ISSUE THREAD

**Issue by ItsMultiHD** [xavave/Mifare-Windows-Tool#34]
Cuando escribo un nuevo tag me da error, tengo el  LibUsbK pero me da error, no se que puedo hacer

**Comment by ItsMultiHD** [comment]
![image](https://user-images.githubusercontent.com/102867353/161388823-210be6ea-64b8-4b20-8994-c10315ca2743.png)

**Comment by xDonatello** [comment]
"not acknowledged"
This is a non-rewritable NFC tag.
