### ISSUE TITLE
[SUGGESTION] Pause during brute force

### ISSUE THREAD

**Issue by xDonatello** [xavave/Mifare-Windows-Tool#35]
Brute force operations occur in cascade, without the possibility to go up in the display viewed.
It would be very comfortable a "Pause" button that allows you to pause the displayed screen, but **without** stopping the brute forcing action.
And then, by pressing "Resume", you return to the real-time display of the brute force operation.

![image](https://user-images.githubusercontent.com/13498803/162580109-b86c9f95-d7a0-4a5a-af73-aa1b856675dd.png)

**Comment by xavave** [comment]
https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.5.8383.26405
