### ISSUE TITLE
Underscore not displayed in Key File

### ISSUE THREAD

**Issue by xDonatello** [xavave/Mifare-Windows-Tool#36]
There is a small graphical error in the display of the keys files names.
In the "EDIT/ADD KEY FILE" screen, if the key file has an underscore in its name, it is not displayed.

![image](https://user-images.githubusercontent.com/13498803/162580379-ef819385-c1f2-46e4-9400-f1d2968a0319.png)

**Comment by xavave** [comment]
hi, thanks for reporting
fixed in https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by xDonatello** [comment]
> hi, thanks for reporting fixed in https://github.com/xavave/Mifare-Windows-Tool/releases/latest

Sorry. The problem is also present in the first reading of a tag.

![image](https://user-images.githubusercontent.com/13498803/177886876-d516fc10-b367-45a6-8131-5b3b8a4e9ba3.png)

**Comment by xavave** [comment]
thanks for reporting ! fixed in https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8225.472
