### ISSUE TITLE
errore conversione dump

### ISSUE THREAD

**Issue by Gio197710** [xavave/Mifare-Windows-Tool#37]
Ciao
Con l'ultima versione di MWT mi compare il seguente messaggio e confermando la conversione il programma si chiude.
Con una versione di MWT più vecchia ( V1.0.7372.34977 )non capita,ma apre il dump correttamente.
Posso sapere come risolvere?
Grazie
![messaggio MWT](https://user-images.githubusercontent.com/104201664/164699728-00a69d98-240b-4934-87d5-c2d08de8237e.PNG)

**Comment by xavave** [comment]
duplicate of #38
