### ISSUE TITLE
Converting an incomplete binary dump

### ISSUE THREAD

**Issue by xDonatello** [xavave/Mifare-Windows-Tool#38]
I open a textual dump (.mct) which only has the first 4 sectors, because the others are empty.
And I convert it to binary.
If I try to open it, **the program crashes**.

It would be convenient if, when converting to binary, the program should automatically **add the empty missing sectors** (up to 15).

Also, to avoid crashing the program, **display a message** indicating that the dump is incomplete.

**Comment by xavave** [comment]
Hi, thanks for your report
I've added an option "Yes" or "No" to convert the dump mct to mwt 
When automatic dump format detection is wrong, you can try to select "No" to the question: _This file looks like a MCT (Mifare classic tool) dump. Do you want to try to convert it automatically to MWT dump?_

https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by xDonatello** [comment]
Now when I open an MCT file (textual dump):
If I select "Yes", the contents of the file are displayed correctly.
If I select "No", a dump with random values is displayed*.

After selecting "Yes", clicking "Save Dump as" I save the dump in binary.
If I try to reopen this dump (.mwt), it asks me again "Yes/No".
If I select "Yes", an error screen is displayed (an exception**), but the program doesn't crash (good).
If I select "No", the contents of the dump are displayed.

I don't know if that was the intention, I'm just informing.

(*)
![image](https://user-images.githubusercontent.com/13498803/177181780-36af0aa6-143d-4e98-aded-7ddeb1cbf28e.png)

(**)
![image](https://user-images.githubusercontent.com/13498803/177181798-2fee0a41-ed11-4849-84dd-b2a2b6c8c05f.png)

**Comment by xDonatello** [comment]
Anyway, saving a binary dump when there are only a few sectors in the file is a bit useless since on MWT it is not possible to select the sectors you want to write (unlike MCT).

So, if possible, would be handy a button that converts an "incomplete" dump to a 1K or 4K dump, adding the missing sectors (empty).
