### ISSUE TITLE
missing vcruntime140d.dll and ucrtbased.dll

### ISSUE THREAD

**Issue by yukunyi** [xavave/Mifare-Windows-Tool#39]
Running nfc-list.exe in the installation package prompts that vcruntime140d.dll and ucrtbased.dll are missing,
It seems that nfc-list.exe was compiled into a debug version causing the problem.
MWT Version: 1.0.8212.2219

**Comment by xavave** [comment]
hi Yukunyi
thank you for your report
I've just recompiled nfc tools in release mode , could you please check attachment below and tell me if it works with this version
[MWT_test.zip](https://github.com/xavave/Mifare-Windows-Tool/files/9017538/MWT_test.zip)
?

**Comment by xavave** [comment]
I've just made a new msi setup with the release compiled nfctools : https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by yukunyi** [comment]
> I've just made a new msi setup with the release compiled nfctools : https://github.com/xavave/Mifare-Windows-Tool/releases/latest


This version is ok, thanks for solving the problem.
