### ISSUE TITLE
Plantage lors du formatage d'usine

### ISSUE THREAD

**Issue by Bigboek** [xavave/Mifare-Windows-Tool#4]
Bonjour,
Merci pour cette application.

Je suis sous win 7, tout fonctionne à merveille mis à part le formatage d'usine.
dès que je clique sur le bouton, l'application ne répond plus et se coupe.

j'ai un message " mifare-classic-format.exe, impossible de démarrer le programme car il manque libcrypto.dll sur votre ordinateur"

J'ai bien entendu procédé à la ré installation du soft, mais le problème persiste.

**Comment by xavave** [comment]
Bonjour,

Pourriez vous vérifier svp  si le fichier libcrypto.dll existe dans le répertoire d'installation suivant (par défaut c'est celui-ci)
    C:\Program Files (x86)\AVXTEC\MWT\nfctools
? 
sinon voici la dll à dézipper et à copier dans C:\Program Files (x86)\AVXTEC\MWT\nfctools dans pour re-tester
[libcrypto.zip](https://github.com/xavave/Mifare-Windows-Tool/files/5158207/libcrypto.zip)

Tenez moi au courant du test , merci 👍

**Comment by Bigboek** [comment]
Bonjour Xavave,
Merci pour la réponse, vous avez devancé ma réponse en faisant un edit du message.

Effectivement je suis sous win 7 64 bits.
J'ai effectué le même test sous win 10 64 bits et j'avais le même problème.

Suite à la mise en place des fichiers "libcrypto&dependencies.zip" tout est rentré en ordre sur le PC sous Win 7.
Pour le pc sous win 10, je testerais ce soir mais ça devrait fonctionner.

Merci beaucoup.

**Comment by xavave** [comment]
> Bonjour Xavave,
> Merci pour la réponse, vous avez devancé ma réponse en faisant un edit du message.
> 
> Effectivement je suis sous win 7 64 bits.
> J'ai effectué le même test sous win 10 64 bits et j'avais le même problème.
> 
> Suite à la mise en place des fichiers "libcrypto&dependencies.zip" tout est rentré en ordre sur le PC sous Win 7.
> Pour le pc sous win 10, je testerais ce soir mais ça devrait fonctionner.
> 
> Merci beaucoup.

dans ce cas je pense qu'on peut clôturer ce ticket
