### ISSUE TITLE
Latest version doesn't write

### ISSUE THREAD

**Issue by xDonatello** [xavave/Mifare-Windows-Tool#40]
The latest released version doesn't write on the tags.
The program doesn't give errors, the writing seems to have been successful. However, re-reading the tag did not make any changes inside.
So the writing didn't happen.

I have also tried the previous versions:
1.0.8211.24900 crashes if I try to read a tag
1.0.8211.42281 shows an error message when I try to read a tag
1.0.8212.2219 works but doesn't write
1.0.8216.17589 same thing as the previous one

No problem with the version 1.0.8033.39813

**Comment by xavave** [comment]
https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by xDonatello** [comment]
Now it works again 👍
Thanks for your work
