### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by MoltenLavaCore** [xavave/Mifare-Windows-Tool#41]
As some other have said, the latest version of mifare windows tool doesn't work correctly when writing a dump to a card (in my case a Skylander to a Gen 1 magic tag) 
1.0.8033.39813 works fine, however.

**Comment by xavave** [comment]
Hi,
Thank you for your report. 
I will then switch back to nfc tools from version 39813

**Comment by xavave** [comment]
https://github.com/xavave/Mifare-Windows-Tool/releases/latest
