### ISSUE TITLE
MifareWindowsTool_v1.0.8223.35321

### ISSUE THREAD

**Issue by Pai91300** [xavave/Mifare-Windows-Tool#42]
Problème MifareWindowsTool_v1.0.8223.35321
![Capture](https://user-images.githubusercontent.com/108943494/178018627-f93eada2-1106-4140-8ce2-c96dbb909edf.JPG)

**Comment by xavave** [comment]
That's weird. could you check in this directory and send me a screenshot of the files you see inside this folder:
C:\Program Files (x86)\AVXTEC\MWT\nfctools

**Comment by Pai91300** [comment]
Bonjour, 


Ci-joint le fichier capture de C:\Program Files (x86)\AVXTEC\MWT\nfctools. 

Merci 


Cordialement 
Patrice 
0624281180 
----- Mail original -----

De: "Xavier Averbouch" ***@***.***> 
À: "xavave/Mifare-Windows-Tool" ***@***.***> 
Cc: "Pai91300" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Juillet 2022 22:17:50 
Objet: Re: [xavave/Mifare-Windows-Tool] MifareWindowsTool_v1.0.8223.35321 (Issue #42) 



That's weird. could you check in this directory and send me a screenshot of the files you see inside this folder: 
C:\Program Files (x86)\AVXTEC\MWT\nfctools

**Comment by Pai91300** [comment]
Bonjour, 


Avec la nouvelle version, c'est ok "MifareWindowsTool_v1.0.8225.472" 
Merci 



Cordialement 
Patrice 
0624281180 
----- Mail original -----

De: "Xavier Averbouch" ***@***.***> 
À: "xavave/Mifare-Windows-Tool" ***@***.***> 
Cc: "Pai91300" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Juillet 2022 22:17:50 
Objet: Re: [xavave/Mifare-Windows-Tool] MifareWindowsTool_v1.0.8223.35321 (Issue #42) 



That's weird. could you check in this directory and send me a screenshot of the files you see inside this folder: 
C:\Program Files (x86)\AVXTEC\MWT\nfctools
