### ISSUE TITLE
Nokia emulated MIFARE Classic 4K SAK 38

### ISSUE THREAD

**Issue by mbino** [xavave/Mifare-Windows-Tool#44]
Trying to read a MIFARE Classic 4k - emulated (6212 Classic) card, MWT comes back with ERROR: Cannot determine card type from SAK

ATQA (2 byte): | SAK (1byte): | ATS/ATR: | Product: | Manufacturer: | UID Bytes:
02 00 | 38 |   | MIFARE Classic 4k - emulated (6212 Classic) | Nokia | 4
08 00 | 38 |   | MIFARE Classic 4k - emulated (6131 NFC) | Nokia | 4

**Comment by xavave** [comment]
Hi. I think it's a mfoc related issue: https://github.com/nfc-tools/mfoc/issues/11

**Comment by mbino** [comment]
Very likely, but that issue was closed in 2015.

**Comment by xavave** [comment]
Yes. I have no idea why it doesn't work for your specific card

**Comment by xavave** [comment]
Is your emulated card on your Nokia device working as well as the original card ? (Could you test it?)

**Comment by xavave** [comment]
no answer from mbino... I'm closing this issue
