### ISSUE TITLE
Failure to decode the card

### ISSUE THREAD

**Issue by xLoksley** [xavave/Mifare-Windows-Tool#45]
Hi when I tried to decode that card, the tool fails decode it. Do you know how can I resolve this problem
![Capture](https://user-images.githubusercontent.com/112327962/187076102-b4686cef-53af-4be3-b6b1-3dbb56d1560d.PNG)
?

**Comment by xavave** [comment]
Hi, which kind of card is it?
Did you try with other cards?
Maybe you should also add some custom keys to decode

**Comment by xLoksley** [comment]
It’s a metro card (Rome city)

**Comment by xLoksley** [comment]
Can you suggest me some customs keys to decode ISO 14443B-2

**Comment by xavave** [comment]
Keys do not depend on card type
You need to find the keys for your card brand. I don't have the custom keys you need but I guess you could google them

**Comment by xLoksley** [comment]
I tried to goggle it. I couldn’t find for metrebus card.
I don’t know really how to resolve this

**Comment by xLoksley** [comment]
It’s  a metro card (Rome city)

**Comment by xavave** [comment]
I don't think it's an issue from mwt. 
As it is working fine with other cards, mauve this king of tag is protected differently
