### ISSUE TITLE
Why is a dump file considered invalid if its length is <1024 ?

### ISSUE THREAD

**Issue by LucasMrqes** [xavave/Mifare-Windows-Tool#46]
Hello,

I noticed that a dump file is considered invalid (when writing or using the diff tool) if its length is < 1024 or > 4096. Why is that ? 
I am trying to copy a card that has only 5 sectors of data on it (0 to 4), so the dump file is considered invalid when I try to write it on an other card or compare it to an other dump. 

I had to convert my dump to txt, add "blank" sectors and convert it back to mfd to successfully write it.

Does this mean that this tool cannot write dumps to mifare mini cards ? 
Would my duplicate card work if the original card is a mifare mini, and the duplicate is a mifare 1K with sectors 5 to 15 left empty ?

**Comment by xavave** [comment]
hi, it should be fixed in the next release soon

**Comment by xavave** [comment]
Hi 
I've updated the prerelease yesterday 
You can download and test it if you want
