### ISSUE TITLE
Wpf Hexeditor Control

### ISSUE THREAD

**Issue by wolfgangschneider** [xavave/Mifare-Windows-Tool#49]
Where can I find the WpfHexeditorControl source? The folder is empty on Github and in source zip file too.
L.G

**Comment by xavave** [comment]
> Where can I find the WpfHexeditorControl source? The folder is empty on Github and in source zip file too.
> 
> L.G

Hi
You can find it here 

https://github.com/abbaye/WpfHexEditorControl

I've customized it in the DLL I provide because it was buggy 
X.
