### ISSUE TITLE
MWT fails to read MiFare Plus 2K

### ISSUE THREAD

**Issue by EngineerLLC** [xavave/Mifare-Windows-Tool#5]
When attempting to read a MiFare Plus EV2 2K card, the card is correctly identified, appears to complete authentication and then appears to halt before displaying any read data.  The "ERROR: while requesting encrypted tag-nonce" message is the only indication.

![MWT-Fail_MF2kP_2020-09-22](https://user-images.githubusercontent.com/29240106/93944269-3382a180-fce9-11ea-941b-2a7410fe76f8.jpg)

**Comment by lesterCrest6** [comment]
I am having the same issue with a Mifare Plus 2K tag.
