### ISSUE TITLE
Driver is not recognized 

### ISSUE THREAD

**Issue by xDerApfelx** [xavave/Mifare-Windows-Tool#50]
When I start the application I get this error
![Screenshot 2022-10-30 152003](https://user-images.githubusercontent.com/117024724/198883659-b160ac0d-6f36-4c85-9630-dbdef7413655.png)
Then i press on ok and install the correct driver again. If I restart the app the error message is shown again.
I did ignore it and pressed on "read Tag" and than this showed up
![Screenshot 2022-10-30 152031](https://user-images.githubusercontent.com/117024724/198883746-42be0a81-891f-479e-976f-2b1ebd54a71b.png)
I installed this too, but the error messages are always there

**Comment by xavave** [comment]
Hi. Can you tell me more precisely which driver you have installed ?
Which rag reader did you plug in ? Acr-122U ? 
Which windows version do tu use ? Windows 10. 64 bits?

**Comment by xDerApfelx** [comment]
Maybe I should mention it before. I ordered the Acr122 but it didn't arrive yet, but I thought this still looks like a problem.
I installed the driver which is required "Msi installer..." for the Acr122 with the version 4.2.8.0. Not sure if was this number but definitely the newest one. I am on windows 11, so it must be bit64

**Comment by xavave** [comment]
> Maybe I should mention it before. I ordered the Acr122 but it didn't arrive yet, but I thought this still looks like a problem.
> 
> I installed the driver which is required "Msi installer..." for the Acr122 with the version 4.2.8.0. Not sure if was this number but definitely the newest one. I am on windows 11, so it must be bit64

I think it will should work after you have received your tag reader and plugged it. I will recheck mwt answer with the acr unplugged tonight

**Comment by xavave** [comment]
Normally, when the ACR122U is not plugged in, you should see a message: ACR 122U doesn't seem to be plugged in
1- When you try to start the ACS unified msi 4280 driver after you had already installed it , can you see this? (modify/Repair/Uninstall) or, something else ?
<img width="387" alt="image" src="https://user-images.githubusercontent.com/3501675/198904030-a10e4a92-aa71-4aaf-8f88-21273ea11d79.png">
2 - did you follow exactly this procedure for libusbk ? https://github.com/xavave/Mifare-Windows-Tool/issues/27#issuecomment-1013957721
3 - for your driver issue, maybe you will need to plug the ACR122U at first, before installing libusbk in order for it to work properly

4 - maybe you could try to use the new beta released a few minutes ago when you'll have your ACR122U ? :)
https://github.com/xavave/Mifare-Windows-Tool/releases/tag/beta1.5.8338.41967

**Comment by xDerApfelx** [comment]
1 - Yes, if i try to reinstall the driver I get the same image with modify/repair/delete
2 - No, I didn't follow any instructions. In my first comment is the second picture which mentions that libusbk is not installed and when I press OK it opens an installation menu, but it does not look like the image in the "#27 comment" you linked.
3 and 4 - I will try everything again when I get my reader

**Comment by xDerApfelx** [comment]
I installed the new Version of your app. with 1.5..... beta. It still says at the very start that the driver is missing. But now it also says after I press on read Tag that libusb-1.0.dll is missing.

**Comment by xavave** [comment]
Okay. Thank you 
I will add libusb1.0 DLL
For the driver as I told you before I think that the driver needs to have ACR122U plugged in for it to work properly

**Comment by xavave** [comment]
could you please extract libusb-1.0.dll from this zip file and copy it to C:\Program Files (x86)\AVXTEC\MWT\nfctools?
[libusb-1.0.dll.zip](https://github.com/xavave/Mifare-Windows-Tool/files/9901368/libusb-1.0.dll.zip)

**Comment by xavave** [comment]
> 2 - No, I didn't follow any instructions. In my first comment is the second picture which mentions that libusbk is not installed and when I press OK it opens an installation menu, but it does not look like the image in the "#27 comment" you linked. 

could you show me how your installation menu looks like please?

**Comment by xDerApfelx** [comment]
> could you please extract libusb-1.0.dll from this zip file and copy it to C:\Program Files (x86)\AVXTEC\MWT\nfctools? [libusb-1.0.dll.zip](https://github.com/xavave/Mifare-Windows-Tool/files/9901368/libusb-1.0.dll.zip)

I did it. Driver is still not found. When I press on read tag there are now two more missing dll 
VCRUNTIME140D.dll and ucrtbased.dll after that the same message is shown which says that the acr122 driver is installed but not the libusbk

**Comment by xDerApfelx** [comment]
> > 2 - No, I didn't follow any instructions. In my first comment is the second picture which mentions that libusbk is not installed and when I press OK it opens an installation menu, but it does not look like the image in the "#27 comment" you linked.
> 
> could you show me how your installation menu looks like please?

Yes here it is
![Screenshot 2022-10-31 153645](https://user-images.githubusercontent.com/117024724/199034302-6242ca58-957c-4772-81b8-1c0bc18dec04.png)
![Screenshot 2022-10-31 153712](https://user-images.githubusercontent.com/117024724/199034352-d1898548-f897-412a-99ef-7274841093ef.png)

After I press OK the two error messages show up mentioned in my comment before

![Screenshot 2022-10-31 153744](https://user-images.githubusercontent.com/117024724/199034520-c35cd6c6-278f-4b28-a42a-6cee03188de5.png)

This one says just it is an installation assistent

![Screenshot 2022-10-31 153819](https://user-images.githubusercontent.com/117024724/199034785-8a6b1382-7cdb-4367-abaa-35f512af9bad.png)

**Comment by xavave** [comment]
thanks, could you download this one : https://sourceforge.net/projects/libusbk/files/latest/download (install/next/next/.../finish)
then search for installed:
![image](https://user-images.githubusercontent.com/3501675/199035768-3d799b21-54b6-42db-b643-53e254bf43f8.png)

then

![image](https://user-images.githubusercontent.com/3501675/199035875-7fb6313c-7a65-4882-a819-da9720a26531.png)

then

![image](https://user-images.githubusercontent.com/3501675/199035978-071c105b-3acf-4443-9eb7-39477b773673.png)

and you will see that's why you will need to wait to get your ACR122U to install libusbk:

If ACR is not plugged in, you CANNOT see the device 0x072f which corresponds to ACR122U, and so , libusbk cannot be installed for ACR122U before you get the device

**Comment by xDerApfelx** [comment]
Installed it, now I wait to get my device shipped. Should be arriving in the next couple of days

**Comment by xDerApfelx** [comment]
> > could you please extract libusb-1.0.dll from this zip file and copy it to C:\Program Files (x86)\AVXTEC\MWT\nfctools? [libusb-1.0.dll.zip](https://github.com/xavave/Mifare-Windows-Tool/files/9901368/libusb-1.0.dll.zip)
> 
> I did it. Driver is still not found. When I press on read tag there are now two more missing dll VCRUNTIME140D.dll and ucrtbased.dll after that the same message is shown which says that the acr122 driver is installed but not the libusbk

I could install these dll by myself but I don't know in which folders in need to put them

**Comment by xavave** [comment]
> Installed it, now I wait to get my device shipped. Should be arriving in the next couple of days

If you find the DLL missing , you can put them in the same folder than libusb-1.0.dll mentioned above

**Comment by xDerApfelx** [comment]
> > Installed it, now I wait to get my device shipped. Should be arriving in the next couple of days
> 
> If you find the DLL missing , you can put them in the same folder than libusb-1.0.dll mentioned above

Yes i will do, but should I download always the newest version? Because at [This](https://de.dll-files.com/vcruntime140d.dll.html) the newest version is for 32 architecture and not 64. Which one do I need

**Comment by xDerApfelx** [comment]
My ACR122 still did not arrived, but I found something different I forgot to show you. When I press on any of the things like read, write or edit this error massege shows up
On the top, nfc list error - application error
The application couldn't started correctly. Press ok to close the application. But when I press OK nothing changes. I am still in MWT. Maybe the error code can help you
![Screenshot 2022-11-06 165345](https://user-images.githubusercontent.com/117024724/200180973-4cc4fc8f-b4ae-4003-9c5f-1806dd8a635a.png)

**Comment by xavave** [comment]
Hi , this error 7b on your message means : nfc-list: ERROR: Unable to open NFC device: acr122_usb:003:002

So if you don't have ACR122 it can display this error. 
Anyway I recommand you to use the latest stable release. Not the beta. When you will use the tag reader fr the first time (when you'll have received it)

**Comment by lonestar125** [comment]
I seem to be encountering exactly all these issues with a similar setup (windows 11, same acr122 driver version) and am now stuck on the error 7b message + the LibUsbK not installed message (although I installed it through usb INF creator). I have also tried with several older versions and it does not seem to have any effect on these errors.

**Comment by xavave** [comment]
> I seem to be encountering exactly all these issues with a similar setup (windows 11, same acr122 driver version) and am now stuck on the error 7b message + the LibUsbK not installed message (although I installed it through usb INF creator). I have also tried with several older versions and it does not seem to have any effect on these errors. 
> 
> 
> 
> Im starting to suspect that this has something to do with windows 11 as a friend with a windows 10 machine managed to get the specific ACR122 reader i am using to work fine.

Which mifare windows tool version did you try ? Did you instal acr 122 u driver before libusbk ? Did you select acr 122u on libusbk (with ACR122U plugged in) ?

**Comment by lonestar125** [comment]
I tried the latest Beta (beta1.5.8338.41967) which after replacing all 3 missing dlls gave me the 7b error.
Then I tried the latest stable version which when pressing either the read or write button simply crashed.
I finally tried version 1.0.8212.2219 which also gave me libusbk missing error and 7b error.

i installed acr122u driver before libusbk and i did select the acr122u in the INF creator tool when doing the install as the device does appear in the list of available devices.

There was also initially a red led then when i installed the ACR driver there was a green one and a after installing libusbk with INF when i plug it in the led is turned off.

**Comment by xavave** [comment]
> I tried the latest Beta (beta1.5.8338.41967) which after replacing all 3 missing dlls gave me the 7b error.
> 
> Then I tried the latest stable version which when pressing either the read or write button simply crashed.
> 
> I finally tried version 1.0.8212.2219 which also gave me libusbk missing error and 7b error. (without touching any of the dlls but they may be saved over from the previous install idk)
> 
> 
> 
> I installed acr122u driver before libusbk and I did select the acr122u in the INF creator tool when doing the install as it does appear in the list of available devices.
> 
> 
> 
> There was also initially a red led. When i installed the ACR driver there was a green one. And finally, after installing libusbk with INF when i plug it in the led is simply turned off.

Please uninstall the beta which is not stable and reinstall latest stable. It's good if no green light on ACR122U it means libusbk is installed correctly. When it crashes do you have any error message ? Which ACR122U version do you have ? A9?

**Comment by lonestar125** [comment]
> > I tried the latest Beta (beta1.5.8338.41967) which after replacing all 3 missing dlls gave me the 7b error.
> > Then I tried the latest stable version which when pressing either the read or write button simply crashed.
> > I finally tried version 1.0.8212.2219 which also gave me libusbk missing error and 7b error. (without touching any of the dlls but they may be saved over from the previous install idk)
> > I installed acr122u driver before libusbk and I did select the acr122u in the INF creator tool when doing the install as it does appear in the list of available devices.
> > There was also initially a red led. When i installed the ACR driver there was a green one. And finally, after installing libusbk with INF when i plug it in the led is simply turned off.
> 
> Please uninstall the beta which is not stable and reinstall latest stable. Could you check after uninstalling and, before reinstalling latest stable, that the c:\program files (x86)\AVXTEC folder is empty ? (If not delete everything under AVXTEC and then reinstall stable ) It's good if no green light on ACR122U it means libusbk is installed correctly. When it crashes do you have any error message ? Which ACR122U version do you have ? A9?

Ok so I completely uninstalled MWT and deleted the c:\program files (x86)\AVXTEC before reinstalling the latest stable version and everything works perfectly now, thanks for the help.

**Comment by xDerApfelx** [comment]
My device arrived today and I needed to install the lib ubsk like in [THIS](https://github.com/xavave/Mifare-Windows-Tool/issues/27) and now everything is perfect 👍👍

**Comment by lonestar125** [comment]
> My device arrived today and I needed to install the lib ubsk like in [THIS](https://github.com/xavave/Mifare-Windows-Tool/issues/27) and now everything is perfect 👍👍

are you using the latest beta or the stable version?

**Comment by xDerApfelx** [comment]
Stable
