### ISSUE TITLE
"Error tag was removed"

### ISSUE THREAD

**Issue by xDerApfelx** [xavave/Mifare-Windows-Tool#52]
Hey man, I got another problem. I installed everthing correclty and plugged in my Acr122. I put a card on it and pressed on write tag. Than an error massage said it needed to be decrupted. After that I press on write tag again, select the "chinese magic unlocked/gen1", select my dump file and press clone. Then this shows up 
![Screenshot 2022-11-08 165833](https://user-images.githubusercontent.com/117024724/200614748-2ced1f7e-b553-4b5c-8081-bf758fd85da8.png)

**Comment by xavave** [comment]
Please search in closed issue before adding a new issue : https://github.com/xavave/Mifare-Windows-Tool/issues/48#issuecomment-1282832527

**Comment by xDerApfelx** [comment]
I tried it, but it does not work. If i use the gen 2 feature it will be written 60 of 64 blocks, but I need all 64/64

**Comment by xDerApfelx** [comment]
Man there is something I do not understand. The nfc cards I have are re writable. But why can't I delete everything on it and then clone a new dump file on it??? Why do I need new cards?

**Comment by xavave** [comment]
> Man there is something I do not understand. The nfc cards I have are re writable. But why can't I delete everything on it and then clone a new dump file on it??? Why do I need new cards?

@xDerApfelx it depends on what you already wrote on your cards. If you clone a dump on it and this dump has blocked ACL it can brick your card
