### ISSUE TITLE
Warning: Unlock Command 1/2

### ISSUE THREAD

**Issue by SheroxGG** [xavave/Mifare-Windows-Tool#53]
Hello! I am getting this error when trying to dump info on NFC. Hope someone can help me out.
![image](https://user-images.githubusercontent.com/34599826/201039987-baab2d92-f3c1-4bb0-b89c-80f7f7d4eaff.png)

**Comment by xavave** [comment]
Hi 
Please check https://github.com/xavave/Mifare-Windows-Tool/issues/52
