### ISSUE TITLE
LibUsbK is installed but libusb-1.0.dll is missing

### ISSUE THREAD

**Issue by Acyone** [xavave/Mifare-Windows-Tool#54]
When I try to read a card, I get this message : 
"The code execution cannot proceed because libusb-1.0.dll was not found. Reinstalling the program may fix this problem."
![image](https://user-images.githubusercontent.com/22574019/203849969-b3b03ac0-2bf8-48c9-825c-b5de26621132.png)

 then this one :
"ACR122U seems to be installed but, NOT the LibUsbK driver. Click OK to install it"
![image](https://user-images.githubusercontent.com/22574019/203848197-0c6f27f1-c599-4445-b6d4-682a8b11b04b.png)

But when I install it, nothing changes, and I get the same message.
My ACR122U does not light up when I install the libusbk driver, only if I install the 

I have tried 
 - unplugging and replugging my ACR122U
 - installing all the drivers the libusbk installer proposes
 - installing a driver via the device manager
 - reinstalling MWT
 - reinstalling ACS

How should I proceed ? 
Thanks

**Comment by xavave** [comment]
please don't use beta version for now, use this one :https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.0.8225.472

**Comment by xavave** [comment]
and about his :My ACR122U does not light up when I install the libusbk driver --> it's normal with libusbk driver and it means libusk is properly installed, if ACR lights up in green, it means taht libusk is not properly installed and MWT will not work

**Comment by xavave** [comment]
and please uninstall beta version and check that C:\Program Files (x86)\AVXTEC\MWT folder is empty, before installing version 1.0.8225.472
if C:\Program Files (x86)\AVXTEC\MWT is not empty, please remove everything inside this folder **before installing version 1.0.8225.472**

**Comment by Acyone** [comment]
Since I posted the issue, I have tried putting the correct dll file I got from https://libusb.info/ in C:\Program Files (x86)\AVXTEC\MWT andit seems to be working now. I will still revert to the last stable version in case I encounter any more problems. Thank you.

**Comment by xavave** [comment]
Hi 
I've updated the pre release yesterday
You can download and test it if you like
