### ISSUE TITLE
no tag detected on reader  /  nfc-list.exe error  /  libsusbk error

### ISSUE THREAD

**Issue by xDerApfelx** [xavave/Mifare-Windows-Tool#57]
I got a new error again. I uninstalled everything from my pc. All the applications, drivers...
Then I first installed your software (MWT)
Then the ACR122u driver (PC msi installer)
And than I installed the LibUsbk driver with your tutorial.
I can start the program without problems, but when I press on read tag this error occurs.
Translation:
nfc list - application error
The application did not started the right way. Press ok to close the application

![1](https://user-images.githubusercontent.com/117024724/207118628-1c66dcef-0c10-4d65-b115-058b22944cfc.png)

After I press ok this is the next error message. I clicked on both but nothing changed.

![2](https://user-images.githubusercontent.com/117024724/207119083-f6cc2396-5a4d-4ca9-aaa9-095c60c065e9.png)

When I press on ok this new window opens. It is the driver installer assistant by windows.

![3](https://user-images.githubusercontent.com/117024724/207119361-2c3a401f-6b17-4725-a7a3-919f3671dbfb.png)

![4](https://user-images.githubusercontent.com/117024724/207119916-ecf9c743-0945-44fe-af7c-1411e50a35a2.png)

**Comment by xavave** [comment]
Hi
I see you have installed the latest beta version. 
If you want to use mwt quickly , I suggest you to uninstall this version and use the previous stable version. 
You can also send me a private message email on xavave@gmail.com. If you install anydesk I could then try to debug directly on your computer for testing

**Comment by xDerApfelx** [comment]
I am using the newest version 1.5.83..... of mwt
I just installed anydesk 
333214916 is the code for anydesk

**Comment by xDerApfelx** [comment]
Yes, I am using 1.5.....
I don't need to use it quickly. I just wanted to try if everything is working properly

**Comment by xavave** [comment]
after checking on xDerApfelx's computer, I switched back to previous nfctools and forced install in administrator mode, because in some cases it was not possible to access MWT folders without admin rights --> new version here: https://github.com/xavave/Mifare-Windows-Tool/releases/latest
