### ISSUE TITLE
Does not work with acr1252

### ISSUE THREAD

**Issue by mariolpantunes** [xavave/Mifare-Windows-Tool#59]
Does not work with acr1252.
Can you add support for the NFC reader/writer acr1252

**Comment by xavave** [comment]
hi,
unfortunately, it depends on libnfc which still not support ACR1252: https://github.com/nfc-tools/libnfc/issues/658

**Comment by xavave** [comment]
Hi @mariolpantunes 
 maybe you can give a try with pcsc drivers from the new MWT prerelease:
https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.6.8408.42890
