### ISSUE TITLE
how to run this code with ACR1281U 

### ISSUE THREAD

**Issue by hmd-design** [xavave/Mifare-Windows-Tool#6]
there is a difference between my own card reader and the one used in the code. I should run this tool with ACR1281U but it is not working with this reader. Can anybody tell me how to change the reader lib in this code? or Does anyone have an experience in adding an special ACR reader lib to a C# project?

**Comment by xavave** [comment]
Hi
You will need to create / find drivers for acr1281u on Linux and re - cross compile libnfc from Linux to windows with these acr 1281u included
