### ISSUE TITLE
Mifare Closes

### ISSUE THREAD

**Issue by GoopIsMe** [xavave/Mifare-Windows-Tool#61]
I have been trying to write to some new cards but whenever I try MWT closes write after I try to have it write. Does anyone have any solutions?

Hi @GoopIsMe 
Which MWT version do you use ?
Could you provide us some screenshots of your operations before crash and when it crashes please?

**Comment by xavave** [comment]
@GoopIsMe please install latest version: https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.5.8408.24604
if you get a warning like this:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/3501675/211197108-25a5b526-5a8a-4d71-ab3d-8a58f831e699.png">
maybe that your antivirus has blocked some of the mandatory files.
Please check in your antivirus and you can add folder: C:\Program Files (x86)\AVXTEC\MWT\nfctools in your antivirus trusted folder
