### ISSUE TITLE
I cant write in the last version

### ISSUE THREAD

**Issue by IndominusAlfa** [xavave/Mifare-Windows-Tool#65]
I´m trying to write a card this morning, but when i update the tool to the last version it send me this error
![Screenshot_3](https://user-images.githubusercontent.com/123368991/214020116-d0577293-d1b1-4459-a945-ff3d7ac0d575.png)
and then send me this warning
![Screenshot_1](https://user-images.githubusercontent.com/123368991/214020186-e1fdc9d1-0972-447b-85f4-c4f1eaf34139.png)
i have all the nfc reader drivers installed but i cannot read/write anyone
¿Could you help me?

**Comment by xavave** [comment]
Hi,

* 1 - Make sure you have uninstalled libusbk driver filter , then unplugged and reppluged your tag reader
* 2 - delete WinSCard.dll in C:\Program Files (x86)\AVXTEC\MWT\nfctools_pcsc

--> https://github.com/xavave/Mifare-Windows-Tool/issues/64

**Comment by xavave** [comment]
could you try with this update ? https://github.com/xavave/Mifare-Windows-Tool/releases/latest

**Comment by IndominusAlfa** [comment]
I actually can write again
thank you for your time

**Comment by xavave** [comment]
> I actually can write again
> 
> thank you for your time
> 
> 

Which tag reader do you have ? ACR122U ?

**Comment by IndominusAlfa** [comment]
yes

**Comment by xavave** [comment]
I didn't have time to fully test my latest release. I'm happy if it works fine then. I hope that "change uid" option in tools will work too. (There still may be a "tag reader not found" issue here

**Comment by xavave** [comment]
> I didn't have time to fully test my latest release. I'm happy if it works fine then. I hope that "change uid" option in tools will work too. (There still might be a "tag reader not found" issue here) --> fixed: https://github.com/xavave/Mifare-Windows-Tool/releases/latest
