### ISSUE TITLE
Unable to open nfc device after libusbk install

### ISSUE THREAD

**Issue by cenzo85** [xavave/Mifare-Windows-Tool#67]
Hi, I have the same problem or quite the same of the "https://github.com/xavave/Mifare-Windows-Tool/issues/11".
If I install the original driver the light of the reader is RED and became GREEN when I put a card on the reader.
After the installation of libusbk the light of the reader swich off (on the list of windows peripheral it appear like correcly installed), so I have the same problem "Unable to read Usb ... "

How can I  undetand if the acr122u is a fake ?

              Hello.
I solved the Problem. I just had a fake acr122u.

_Originally posted by @CraggerYT in https://github.com/xavave/Mifare-Windows-Tool/issues/11#issuecomment-789769124_

**Comment by xavave** [comment]
> Hi, I have the same problem or quite the same of the "https://github.com/xavave/Mifare-Windows-Tool/issues/11".
> 
> If I install the original driver the light of the reader is RED and became GREEN when I put a card on the reader.
> 
> After the installation of libusbk the light of the reader swich off (on the list of windows peripheral it appear like correcly installed), so I have the same problem "Unable to read Usb ... "
> 
> 
> 
> How can I  undetand if the acr122u is a fake ?
> 
> 
> 
> 
> 
> 
> 
> 
> 
>               Hello.
> 
> I solved the Problem. I just had a fake acr122u.
> 
> 
> 
> _Originally posted by @CraggerYT in https://github.com/xavave/Mifare-Windows-Tool/issues/11#issuecomment-789769124_
> 
>             

Hello,
Not fake ACR122U. 
Just read here: https://github.com/xavave/Mifare-Windows-Tool/releases/tag/1.6.8408.42890

For all versions after this release you need to UNINSTALL LIBUSBK. 
Latest version: https://github.com/xavave/Mifare-Windows-Tool/releases/latest
