### ISSUE TITLE
chinese tag gen2 (writing uid)

### ISSUE THREAD

**Issue by rachkeulube** [xavave/Mifare-Windows-Tool#7]
hello, from france
is it possible to update your software to change uid of chinese tag gen2 as do official mct in android ?
may be keeping the "old" nfc-mfsetuid a1b2c3d4
and combining the "new" one, hf mf wrbl 0 B FFFFFFFFFFFF a473f601200804006263646566676869 (being very carreful with bcc calculating)

merci ^^

**Comment by xavave** [comment]
Hello from france too 👍 
 hf mf wrbl c'est une commande spécifique pour le lecteur PROXMARK 3 , cette commande n'existe pas pour le lecteur ACR122U  et mon logiciel ne prend pas en charge le PROXMARK

**Comment by rachkeulube** [comment]
re bonjour, 
je ne sais pas si vous recevrez ce message. 


permettez moi d'insister, la commande proxmark3 est un exemple. 
je me suis permis de poser la question vu que le mct officiel le fait sous android. 
peut etre pourriez vous implementer la commande dans votre version. 
ou une similaire d'ecriture sur le block 0 par une clé connue et un controle bcc. 


merci encore, desolé a l'avance de vous poluer. 
jeanluc 
----- Mail original -----



Closed #7 .

**Comment by xavave** [comment]
> 
> re bonjour, 
> je ne sais pas si vous recevrez ce message. 
> 
> 
> permettez moi d'insister, la commande proxmark3 est un exemple. 
> je me suis permis de poser la question vu que le mct officiel le fait sous android. 
> peut etre pourriez vous implementer la commande dans votre version. 
> ou une similaire d'ecriture sur le block 0 par une clé connue et un controle bcc. 
> 
> 
> merci encore, desolé a l'avance de vous poluer. 
> jeanluc 
> ----- Mail original -----
> 
> 
> 
> Closed #7 . 
> — 
> You are receiving this because you authored the thread. 
> Reply to this email directly, view it on GitHub , or unsubscribe . 
> 

You may ask this to libnfc team as mifare windows tool use libnfc for tag operations
