### ISSUE TITLE
License and credits

### ISSUE THREAD

**Issue by ikarus23** [xavave/Mifare-Windows-Tool#8]
Hi! I appreciate to replicate the functionality of the MCT Android app to Windows. It must mean that my app good tool that is missing on this platform.

However, it is kind of a dick move to do it this way. It is clear that you used the icons and even copied and modified my logo. I haven't had a closer look to the code, but I guess there are some copy&modify as well?! And all this without any credit? 

This violates some licenses. The icons, the logo and maybe the code. Maybe this is just a misunderstanding, but regardless, I would really appreciate if you fix this!

https://github.com/ikarus23/MifareClassicTool#license

**Comment by xavave** [comment]
Hi 
Sorry for this issue 
I didn't copy the source code, only the logos and icons but I will update the license credits immediatly

**Comment by xavave** [comment]
Hi Gerhard
Very sorry for this
I've updated the main page :
https://github.com/xavave/Mifare-Windows-Tool

Regards,
xavave

**Comment by ikarus23** [comment]
Hi xavave, thanks for updating the readme.
